trace:
  verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        sock-path: /tmp/dnstap.sock

  loggers:
    - name: out
      stdout:
        mode: text

  routes:
    - src:
        - tap
      dst:
        - out
