trace:
  verbose: true

multiplexer:
  collectors:
    - name: pdns
      powerdns:
        listen-ip: 0.0.0.0
        listen-port: 6001

  loggers:
    - name: out
      stdout:
        mode: text

  routes:
    - src:
        - pdns
      dst:
        - out
