trace:
  verbose: true

collectors:
  dnstap:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 6000

loggers:
  stdout:
    enable: false

  webserver:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 8080
    top-max-items: 100
    basic-auth-login: admin
    basic-auth-pwd: changeme

