trace:
  verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000

  loggers:
    - name: out
      stdout:
        mode: text

  routes:
    - src:
        - tap
      dst:
        - out
