# If turned on, log some applications messages
trace:
  # debug informations
  verbose: true
  # filename is the file to write logs to.
  filename: ""
  # maximum size in megabytes of the log file it gets rotated
  max-size: 10
  # maximum number of old log files to retain
  max-backups: 10

# list of supported collectors
collectors:

  dnstap:
    # to enable, set the enable to true
    enable: true
    # listen on ip
    listen-ip: 0.0.0.0
    # listening on port
    listen-port: 6000
    # unix socket path
    sock-path: null
    # tls support
    tls-support: false
    # certificate server file
    cert-file: ""
    # private key server file
    key-file: ""

  dns-sniffer:
    # to enable, set the enable to true
    enable: true
    # filter on source and destination port
    port: 53
    # if "" bind on all interfaces
    device: wlp2s0
    # capture dns queries
    capture-dns-queries: true
    # capture dns replies
    capture-dns-replies: true

# settings for subprocessors
subprocessors:

  # IP-Addresses are anonymities by zeroing the host-part of an address.
  anonymize-ip: false

  # The cache is used to compute latency between replies and queries
  # Ttl in second 
  cache-ttl: 10

  # Server identity, if empty  the hostname is used
  # This settings is used in dnstap generator as dnstap-identity
  server-id: ""

  # filtering feature
  filtering:
    # regexp to ignore incoming qname
    ignore-qname: ""
    # log queries or not
    log-queries: true
    # log replies or not
    log-replies: true

  # geoip maxmind support
  geoip:
    # path file to your database
    db-file: ""

# list of loggers
loggers:

  stdout:
    # to enable, set the enable to true
    enable: true
    # output format: text|json
    mode: text

  webserver:
    # to enable, set the enable to true
    enable: true
    # listening IP
    listen-ip: 0.0.0.0
    # listening port
    listen-port: 8080
    # default number of items to return
    top-max-items: 100
    # default login
    basic-auth-login: admin
    # default password
    basic-auth-pwd: changeme
    # tls support
    tls-support: false
    # certificate server file
    cert-file: ""
    # private key server file
    key-file: ""
    # prometheus suffix
    prometheus-suffix: "dnscollector"

  logfile:
    # to enable, set the enable to true
    enable: false
    # output logfile name
    file-path: null
    # maximum size in megabytes of the file before rotation
    max-size: 100
    # maximum number of files to retain.
    max-files: 10
    # flush every x seconds
    flush-interval: 10

  dnstap:
    # to enable, set the enable to true
    enable: false
     # remote address
    remote-address: 10.0.0.1
    # remote tcp port
    remote-port: 6000
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false

  tcpclient:
    # to enable, set the enable to true
    enable: false
    # network transport to use: tcp|unix
    transport: tcp
    # remote address
    remote-address: 127.0.0.1
    # remote tcp port
    remote-port: 9999
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false
    # output format: text|json
    mode: json

  syslog:
    # to enable, set the enable to true
    enable: false
    # Set the syslog logging severity 
    severity: INFO
    # Set the syslog logging facility 
    facility: DAEMON
    # Transport to use to a remote log daemon or local one
    # local|tcp|udp|unix
    transport: local
    # Remote address host:port
    remote-address: ""

  fluentd:
    # to enable, set the enable to true
    enable: false
    # network transport to use: tcp|unix
    transport: tcp
    # remote address
    remote-address: 127.0.0.1
    # remote tcp port
    remote-port: 24224
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # tag name
    tag: "dns.collector"
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false

  pcapfile:
    # to enable, set the enable to true
    enable: false
    # output logfile name
    file-path: null
    # maximum size in megabytes of the file before rotation
    max-size: 1
    # maximum number of files to retain.
    max-files: 3