# If turned on, log some applications messages
trace:
  # debug informations
  verbose: true
  # filename is the file to write logs to.
  filename: ""
  # maximum size in megabytes of the log file it gets rotated
  max-size: 10
  # maximum number of old log files to retain
  max-backups: 10

# list of supported collectors
collectors:

  dnstap:
    # to enable, set the enable to true
    enable: true
    # listen on ip
    listen-ip: 0.0.0.0
    # listening on port
    listen-port: 6000
    # unix socket path
    sock-path: null
    # tls support
    tls-support: false
    # certificate server file
    cert-file: "/home/denis/Lab/logs-dnstap/stunnel.crt"
    # private key server file
    key-file: "/home/denis/Lab/logs-dnstap/stunnel.key"

  dns-sniffer:
    # to enable, set the enable to true
    enable: false
    # filter on source and destination port
    port: 53
    # if "" bind on all interfaces
    device: wlp2s0
    # capture dns queries
    capture-dns-queries: true
    # capture dns replies
    capture-dns-replies: true

  tail:
    # to enable, set the enable to true
    enable: false
    # file to follow
    file-path: null
    # Use the exact layout numbers described https://golang.org/src/time/format.go
    time-layout: "2006-01-02T15:04:05.999999999Z07:00"
    # regexp pattern for queries
    # example for unbound: "query: (?P<queryip>[^ ]*) (?P<domain>[^ ]*) (?P<qtype>[^ ]*)"
    pattern-query: "^(?P<timestamp>[^ ]*) (?P<identity>[^ ]*) (?P<qr>.*_QUERY) (?P<rcode>[^ ]*)
      (?P<queryip>[^ ]*) (?P<queryport>[^ ]*) (?P<family>[^ ]*) (?P<protocol>[^ ]*)
      (?P<length>[^ ]*)b (?P<domain>[^ ]*) (?P<qtype>[^ ]*) (?P<latency>[^ ]*)$"
    # regexp pattern for replies
    # example for unbound: "reply: (?P<queryip>[^ ]*) (?P<domain>[^ ]*) (?P<qtype>[^ ]*) IN (?P<rcode>[^ ]*) (?P<latency>[^ ]*)"
    pattern-reply: "^(?P<timestamp>[^ ]*) (?P<identity>[^ ]*) (?P<qr>.*_RESPONSE) (?P<rcode>[^ ]*)
      (?P<queryip>[^ ]*) (?P<queryport>[^ ]*) (?P<family>[^ ]*) (?P<protocol>[^ ]*) (?P<length>[^ ]*)b
      (?P<domain>[^ ]*) (?P<qtype>[^ ]*) (?P<latency>[^ ]*)$"

# settings for subprocessors
subprocessors:
  # Statistics engine
  statistics:
    # default number of items on top 
    top-max-items: 100
    # expected common qtype list, other will be considered as suspicious
    common-qtypes: [ "A", "AAAA", "CNAME", "TXT", "PTR", "NAPTR", "DNSKEY", "SRV", "SOA", "NS", "MX", "DS" ]
    # a length greater than this value will be considered as suspicious
    threshold-qname-len: 80
    # a size greater than this value will be considered as suspicious
    # value in bytes
    threshold-packet-len: 1000
    # threshold to set a domain considered as slow, value in second
    threshold-slow: 0.5

  # IP-Addresses are anonymities by zeroing the host-part of an address.
  anonymize-ip: false

  # Convert all domain to lowercase
  qname-lowercase: true

  # The cache is used to compute latency between replies and queries
  # Ttl in second 
  cache-ttl: 10

  # Server identity, if empty  the hostname is used
  # This settings is used in dnstap generator as dnstap-identity
  server-id: ""

  # filtering feature
  filtering:
    # regexp to ignore incoming qname
    ignore-qname: ""
    # send queries to configured loggers or or not
    log-queries: true
    # send replies to configured loggers or not
    log-replies: true

  # geoip maxmind support
  geoip:
    # path file to your database
    db-file: ""

  # specific the default text log format used on all loggers supporting this mode
  # all available directives:
  # - timestamp: timestamp rfc3339 format, with nano support
  # - identity: dnstap identity
  # - qr: query or reply flag
  # - operation: dnstap operation
  # - rcode: dns return code
  # - queryip: dns query ip
  # - queryport: dns query port
  # - responseip: dns response ip
  # - responseport: dns response port
  # - id: dns id
  # - family: ip protocol version INET or INET6
  # - protocol: protocol UDP, TCP
  # - length: the length of the query or reply
  # - qtype: dns qtype
  # - qname: dns qname
  # - latency: computed latency between queries and replies
  # - answercount: the number of answer
  # - country: country iso code
  # - ttl: answer ttl, only the first one
  # - answer: rdata answer, only the first one, prefer to use the JSON format if you wamt all answers
  text-format: "timestamp identity qr operation rcode queryip queryport family protocol length qname qtype latency ttl"

# list of loggers
loggers:

  stdout:
    # to enable, set the enable to true
    enable: true
    # output format: text|json
    mode: text
    # output text format, please refer to the default text format to see all available directives 
    # use this parameter if you want a specific format
    text-format: ""

  webserver:
    # to enable, set the enable to true
    enable: true
    # listening IP
    listen-ip: 0.0.0.0
    # listening port
    listen-port: 8080
    # default login
    basic-auth-login: admin
    # default password
    basic-auth-pwd: changeme
    # tls support
    tls-support: false
    # certificate server file
    cert-file: ""
    # private key server file
    key-file: ""
    # prometheus suffix
    prometheus-suffix: "dnscollector"

  logfile:
    # to enable, set the enable to true
    enable: false
    # output logfile name
    file-path:  null
    # maximum size in megabytes of the file before rotation
    # A minimum of max-size*max-files megabytes of space disk must be available
    max-size: 100
    # maximum number of files to retain.
    # Set to zero if you want to disable this feature
    max-files: 10
    # flush buffer to log file every X seconds
    flush-interval: 10
    # compress log file
    compress: false
    # compress interval
    # checking every X seconds if new log files must be compressed
    compress-interval: 5
    # output format: text|json
    mode: text
    # output text format, please refer to the default text format to see all available directives 
    # use this parameter if you want a specific format
    text-format: ""
    # run external script after each file rotation
    postrotate-command: null
    # delete file on script success
    postrotate-delete-success: true

  dnstap:
    # to enable, set the enable to true
    enable: false
     # remote address
    remote-address: 10.0.0.1
    # remote tcp port
    remote-port: 6000
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false

  tcpclient:
    # to enable, set the enable to true
    enable: false
    # network transport to use: tcp|unix
    transport: tcp
    # remote address
    remote-address: 127.0.0.1
    # remote tcp port
    remote-port: 9999
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false
    # output format: text|json
    mode: json
    # output text format, please refer to the default text format to see all available directives 
    # use this parameter if you want a specific format
    text-format: ""

  syslog:
    # to enable, set the enable to true
    enable: false
    # Set the syslog logging severity 
    severity: INFO
    # Set the syslog logging facility 
    facility: DAEMON
    # Transport to use to a remote log daemon or local one
    # local|tcp|udp|unix or tcp+tls
    transport: local
    # Remote address host:port
    remote-address: ""
    # output text format, please refer to the default text format to see all available directives 
    # use this parameter if you want a specific format
    text-format: ""
    # output format: text|json
    mode: text
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false

  fluentd:
    # to enable, set the enable to true
    enable: false
    # network transport to use: tcp|unix
    transport: tcp
    # remote address
    remote-address: 127.0.0.1
    # remote tcp port
    remote-port: 24224
    # unix socket path
    sock-path: null
    # interval in second between retry reconnect
    retry-interval: 5
    # tag name
    tag: "dns.collector"
    # enable tls
    tls-support: false
    # insecure skip verify
    tls-insecure: false

  pcapfile:
    # to enable, set the enable to true
    enable: false
    # output logfile name
    file-path: null
    # maximum size in megabytes of the file before rotation
    max-size: 100
    # maximum number of files to retain.
    max-files: 10
    # compress pcap file
    compress: false
    # compress interval
    # checking every X seconds if new log files must be compressed
    compress-interval: 5
    # run external script after each file rotation
    postrotate-command: null
    # delete file on script success
    postrotate-delete-success: true
