trace:
  verbose: true

collectors:
  dnstap-unix:
    enable: false
    sock-path: null

  dnstap-tcp:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 6000

generators:
  stdout:
    enable: true

  webserver:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 8080
    top-max-items: 100
    basic-auth-login: admin
    basic-auth-pwd: changeme

  logfile:
    enable: false
    file-path: null
    max-size: 100
    max-files: 10
    log-queries: true
    log-replies: true

  dnstap-tcp:
    enable: false
    remote-ip: 10.0.0.1
    remote-port: 6000
    retry-interval: 5
    dnstap-identity: dnscollector

  dnstap-unix:
    enable: false
    sock-path: null
    retry-interval: 5
    dnstap-identity: dnscollector

  json-tcp:
    enable: true
    remote-ip: 127.0.0.1
    remote-port: 9999
    retry-interval: 5