verbose: false
server-id: ""

# list of supported collectors
collectors:
  # dnstap logging support with unix socket. To enable, set the enable to true
  dnstap-unix:
    enable: false
    # unix socket path
    sock-path: null

  dnstap-tcp:
    enable: false
    listen-ip: 0.0.0.0
    listen-port: 6000

  # raw sniffer
  dns-sniffer:
    enable: true
    # filter on source and destination port
    port: 53
    # if "" bind on all interfaces
    device: wlp2s0
    identity: dnscollector
    # capture dns queries
    capture-dns-queries: true
    # capture dns replies
    capture-dns-replies: true

# list of generators
generators:
  stdout:
    enable: true
    mode: text

  webserver:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 8080
    top-max-items: 100
    basic-auth-login: admin
    basic-auth-pwd: changeme

  logfile:
    enable: false
    file-path: null
    max-size: 100
    max-files: 10
    log-queries: true
    log-replies: true

  dnstap-tcp:
    enable: false
    remote-ip: 10.0.0.1
    remote-port: 6000
    retry-interval: 5
    dnstap-identity: dnscollector

  dnstap-unix:
    enable: false
    sock-path: null
    retry-interval: 5
    dnstap-identity: dnscollector

  json-tcp:
    enable: false
    remote-ip: 127.0.0.1
    remote-port: 9999
    retry-interval: 5