# If turned on, log some debug informations
verbose: true
# Server identity, if empty  the hostname is used
server-id: ""

# list of supported collectors
collectors:
  # To enable, set the enable to True
  dnstap-unix:
    enable: false
    # unix socket path
    sock-path: null

  # To enable, set the enable to True
  dnstap-tcp:
    enable: false
    # listen on ip
    listen-ip: 0.0.0.0
    # listening on port
    listen-port: 6000

  # To enable, set the enable to True
  dns-sniffer:
    enable: true
    # filter on source and destination port
    port: 53
    # if "" bind on all interfaces
    device: wlp2s0
    # capture dns queries
    capture-dns-queries: true
    # capture dns replies
    capture-dns-replies: true

# settings for processors
processors:
  filtering:
    # regexp to ignore incoming qname
    ignore-qname: ""
    # log queries or not
    log-queries: true
    # log replies or not
    log-replies: true

  geoip:
    # path file to your database
    db-file: ""

# list of generators
generators:
  # To enable, set the enable to True
  stdout:
    enable: true
    # text|json
    mode: text

  # To enable, set the enable to True
  webserver:
    enable: true
    # listening IP
    listen-ip: 0.0.0.0
    # listening port
    listen-port: 8080
    # default number of items to return
    top-max-items: 100
    # default login
    basic-auth-login: admin
    # default password
    basic-auth-pwd: changeme

  # To enable, set the enable to True
  logfile:
    enable: false
    # output logfile name
    file-path: null
    # maximum size of each in Mbit
    max-size: 100
    # maximum number of file
    max-files: 10
    # log queries or not
    log-queries: true
    # log replies or not
    log-replies: true

  # To enable, set the enable to True
  dnstap-tcp:
    enable: false
    remote-ip: 10.0.0.1
    remote-port: 6000
    retry-interval: 5
  
  # To enable, set the enable to True
  dnstap-unix:
    enable: false
    sock-path: null
    retry-interval: 5

  # To enable, set the enable to True
  json-tcp:
    enable: false
    remote-ip: 127.0.0.1
    remote-port: 9999
    retry-interval: 5