openapi: 3.0.2
info:
  title: Swagger for dnscollector tool
  version: 3.0.0
  description: This is a swagger for the API of the dnscollector.
  contact:
    email: d.machard@gmail.com
  license:
    name: MIT
    url: 'https://github.com/dmachard/go-dnscollector/blob/main/LICENSE'
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8080/'
paths:
  /metrics:
    get:
      responses:
        '200':
          description: Metrics in prometheus format
          content:
            text/plain:
              schema:
                type: string
      summary: Get metrics
  /reset:
    get:
      responses:
        '200':
          description: Reset metrics
          content:
            text/plain:
              schema:
                type: string
      summary: Reset metrics
security: []
externalDocs:
  url: 'https://github.com/dmachard/go-dnscollector'