name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - uses: actions/checkout@v2
      with:
        path: app

    - uses: actions/checkout@v2
      with:
        repository: dmachard/go-dnstap-generator
        path: gen

    - name: Install additionnal libraries
      run: |
        sudo apt-get install libpcap-dev
        
    - name: Build
      run: |
        cd app/
        go build .
        cd ../gen/
        go build .

    - name: Loading testing
      run: |
        cd app/
        sudo python3 -m unittest tests.bench -v