name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - uses: actions/checkout@v2
      with:
        path: app

    - uses: actions/checkout@v2
      with:
        repository: dmachard/go-dnstap-generator
        path: gen

    - name: Build
      run: |
        cd app/
        go build .
        cd ../gen/
        go build .