name: Publish

on:
  release:
    types: [published]

jobs:

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Version=${{ github.event.release.tag_name }}'" -o go-dnscollector *.go
          tar -cvzf go-dnscollector_${{ github.event.release.tag_name }}_linux_amd64.tar.gz go-dnscollector config.yml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: go-dnscollector_${{ github.event.release.tag_name }}_linux_amd64.tar.gz

  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build --build-arg VERSION=${{ github.event.release.tag_name }} . --file Dockerfile -t go-dnscollector

    - name: Tag image
      run: |
        docker tag go-dnscollector dmachard/go-dnscollector:${{ github.event.release.tag_name }}
        docker tag go-dnscollector dmachard/go-dnscollector:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/go-dnscollector:latest
        docker push dmachard/go-dnscollector:${{ github.event.release.tag_name }}