name: Publish

on:
  release:
    types: [published]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-dnslogger *.go
          tar -cvzf go-dnslogger_${{ github.event.release.tag_name }}_linux_amd64.tar.gz go-dnslogger config.yml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: go-dnslogger_${{ github.event.release.tag_name }}_linux_amd64.tar.gz