name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        package: ['dnsmessage', 'collectors', 'generators']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Test ${{ matrix.package }}
      run: go test -timeout 5s ./${{ matrix.package }}/ -cover -v

  int:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        package: ['config', 'clientquery_dnstaptcp', 'clientquery_dnstapunix' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - name: build binary
      run: go build

    - name: Test ${{ matrix.package }}
      run: |
        sudo python3 -m pip install dnstap_pb fstrm dnspython
        sudo python3 -m pip install --upgrade protobuf
        sudo python3 -m unittest tests.${{ matrix.package }} -v

  e2e-coredns:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        coredns: [ '1.8.4' ]
        mode: [ 'tcp', 'unix' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - name: build binary
      run: go build

    - name: Deploy coredns docker image
      run: |
        sudo docker run -d --network="host" --name=coredns -v $PWD/tests/:$PWD/tests/ -v /tmp/:/tmp/ coredns/coredns:${{ matrix.coredns }} -conf $PWD/tests/coredns_${{ matrix.package }}.conf
        sudo docker logs coredns > /tmp/core.out
        sudo cat /tmp/core.out

    - name: Test ${{ matrix.mode }}
      run: |
        sudo python3 -m pip install dnstap_pb fstrm dnspython
        sudo python3 -m pip install --upgrade protobuf
        sudo python3 -m unittest tests.dnsquery_dnstap${{ matrix.mode }} -v

  e2e-dnsdist:
    runs-on: ubuntu-20.04
    env:
      COLLECTOR_USER: pdns

    strategy:
      matrix:
        dnsdist: [ '16' ]
        mode: [ 'tcp', 'unix' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - name: build binary
      run: go build

    - name: add pdns user
      run: |
        sudo addgroup --system --gid 953 pdns
        sudo adduser --system --disabled-password --no-create-home -uid 953 --gid 953 pdns

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist_${{ matrix.mode }}.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro -v /tmp/:/tmp/ powerdns/dnsdist-${{ matrix.dnsdist }}

    - name: Test ${{ matrix.mode }}
      run: |
        sudo python3 -m pip install dnstap_pb fstrm dnspython
        sudo python3 -m pip install --upgrade protobuf
        sudo python3 -m unittest tests.dnsquery_dnstap${{ matrix.mode }} -v


