name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package: ['dnsmessage', 'collectors', 'generators']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Test ${{ matrix.package }}
      run: go test -timeout 5s ./${{ matrix.package }}/ -cover -v