name: go tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev:
    strategy:
      matrix:
        os-version: ['ubuntu-22.04', 'macos-11']
        go-version: ['1.19']
        package: ['dnsutils', 'collectors', 'loggers', 'transformers']
    
    runs-on: ${{ matrix.os-version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up Go for root
      run: |
        sudo ln -sf `which go` `sudo which go` || true
        sudo go version
        
    - name: Test ${{ matrix.package }}
      run: sudo go test -timeout 10s ./${{ matrix.package }}/ -cover -v
