name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package: ['dnsmessage', 'collectors', 'generators']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Test ${{ matrix.package }}
      run: go test -timeout 5s ./${{ matrix.package }}/ -cover -v

  int:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package: ['config', 'dnstap']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-python@v2

    - name: build binary
      run: go build

    - name: Test ${{ matrix.package }}
      run: |
        sudo python3 -m pip install dnstap_pb fstrm dnspython
        sudo python3 -m unittest tests.${{ matrix.package }} -v