name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2

    - name: Test dnsmessage
      run: go test -timeout 5s ./dnsmessage/ -cover -v

    - name: Test generators
      run: go test -timeout 5s ./generators/ -cover -v